# -*- coding: utf-8 -*-
"""TASK-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18hDU10Upn_oTvYrCGza-u4UaHj51OZBz

**PRODIGY INFOTECH INTERNSHIP**

**TASK** **1**:Create a Bar Chart or Histogram to visualize the distribution of a categorical variable,such as the distribution of ages or genders in a popluation.

**DONE** **BY**: SUSMITA JEVOOR

**Email:**smita.jevoor@gmail.com

*Importing* *the* *Dataset*
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import io

from google.colab import files
uploaded=files.upload()

df=pd.read_csv('world_pop.csv')
df

df.shape

df.info

df.describe()

df.isnull().sum()

df.dropna(inplace=True)

df_1=df.drop_duplicates()

df_1.info

df.sample()

total_population=df[df['Indicator Code']=='SP.POP.TOTL']
total_population.head()

total_population_sort=total_population.sort_values(by='2022',ascending=False)
total_population_sort

"""GET TOP 5 COUNTRIES WITH THE HIGHEST POPULATON FOR 2022"""

total_highest_population=total_population_sort.head(5)
print("Top 5 countries with the highest populaion in 2022")
total_highest_population

"""**DATA** **VISUALIZATION**"""

def add_value_labels(ax,spacing=10):
  for rect in ax.patches:
    x=rect.get_x()+rect.get_width()/2
    y=rect.get_height()-3

    va='bottom' if y>0 else 'top'
    label='()'.format(y)
    y_shift=spacing*(1 if y>=0 else -1)
    ax.annotate(label,(x,y),xytext=(0,y_shift),textcoords='offset points', ha='center',va=va)

"""TOP 10 COUNTRIES OF TOTAL POPULATION IN YEAR 2022 AND 2000"""

plt.figure(figsize=(20,15))
plt.rcParams['axes.facecolor']=='black'

plt.subplot(2,2,1)
plot=sns.barplot(x="2022",y="Country Name",data=total_highest_population,palette="viridis")
plt.title("Top 10 countries Of Total Population (2022)")
plt.xlabel("Total population")
plt.ylabel("country")
add_value_labels(plot)

plt.subplot(2,2,2)
plot=sns.barplot(x="2000",y="Country Name",data=total_highest_population, palette="viridis")
plt.title("Top Ten countries of Total Population in 2000")
plt.xlabel("Total population")
plt.ylabel("country")
add_value_labels(plot)

plt.tight_layout()

"""TOP 10 COUNTRIES OF TOTAL POPULATION IN YEAR 1999 AND 1989"""

plt.figure(figsize=(20,15))
plt.rcParams['axes.facecolor']=="black"

plt.subplot(2,2,1)
plot=sns.barplot(x='1999',y="Country Name", data=total_highest_population, palette="mako")
plt.title("Top Ten countries Of Total Population 1999")
plt.xlabel("Total population")
plt.ylabel("country")
add_value_labels(plot)

plt.subplot(2,2,2)
plot=sns.barplot(x='1989',y="Country Name", data=total_highest_population,palette="mako")
plt.title("Top Ten countries Of Total Population 1989")
plt.xlabel("Total population")
plt.ylabel("country")
add_value_labels(plot)

plt.tight_layout()

"""TOP 10 COUNTRIES OF TOTAL POPULATION IN YEAR 1960 AND 2022"""

plt.figure(figsize=(20,13))
plt.rcParams['axes.facecolor']=="black"

plt.subplot(2,2,1)
plot=sns.lineplot(x='1960',y="Country Name", data=total_highest_population, palette="coolwarm")
plt.title("Top Ten countries Of Total Population 1960")
plt.xlabel("Total population")
plt.ylabel("country")
add_value_labels(plot)

plt.subplot(2,2,2)
plot=sns.lineplot(x='2022',y="Country Name", data=total_highest_population,palette="coolwarm")
plt.title("Top Ten countries Of Total Population 2022")
plt.xlabel("Total population")
plt.ylabel("country")
add_value_labels(plot)

plt.tight_layout()
plt.show()

"""BOTTOM 10 COUNTRIES WITH THE HIGHEST POPULATION"""

total_population_sort_bt=total_population.sort_values(by='2022',ascending=True)
total_population_sort_bt

top_ten_bt_countries=total_population_sort_bt.head(10)
print("Top ten bottom Countries of Total Population:")
print(top_ten_bt_countries)

"""BOTTOM TEN COUNTRIES OF TOTAL POPULATION IN YEAR 2022 AND 2000"""

plt.figure(figsize=(20,15))
plt.rcParams['axes.facecolor']=="black"

plt.subplot(2,2,1)
plot=sns.scatterplot(x='2022',y="Country Name", data=top_ten_bt_countries, palette="coolwarm")
plt.title("Bottom Ten countries Of Total Population 2022")
plt.xlabel("Total population")
plt.ylabel("country")
add_value_labels(plot)

plt.subplot(2,2,2)
plot=sns.scatterplot(x='2000',y="Country Name", data=top_ten_bt_countries,palette="coolwarm")
plt.title("Bottom countries Of Total Population 2000")
plt.xlabel("Total population")
plt.ylabel("country")
add_value_labels(plot)

plt.tight_layout()

"""10 BOTTOM COUNTRIES OF TOTTAL POPULATION 1960"""

plt.figure(figsize=(20,15))
plt.rcParams['axes.facecolor']=="black"

plt.subplot(2,2,1)
plot=sns.barplot(x='1960',y="Country Name", data=top_ten_bt_countries, palette="coolwarm")
plt.title("Bottom Ten countries Of Total Population 1960")
plt.xlabel("Total population")
plt.ylabel("country")
add_value_labels(plot)

plt.tight_layout()